import { Inter ,Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({weight: [ "200","300","400","500","600","700","800"], subsets: ["latin"] });

export const metadata = {
  title: "Pet-Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className  + " relative bg-custom-color-2 text-[#373737]"}>
        <div className=" sticky top-0">
          <Navbar/>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
